/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sala221
 */
public class FrmAsignaciones extends javax.swing.JFrame {

    /**
     * Creates new form FrmAsignaciones
     */
    public FrmAsignaciones() {
        initComponents();
         cargarBD();
    }
    
  
    public void cargarBD(){
        try {
            Connection con=null;
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/consultorio_juridico","root","");
           Statement st=con.createStatement();
           ResultSet rs=st.executeQuery("select PrimNomb, SeguNomb, PrimApell, SeguApe from terceros;");
         jComboListado.removeAllItems(); 
           while(rs.next()){
             jComboListado.addItem(rs.getString(1));
           }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmAsignaciones.class.getName()).log(Level.SEVERE, null, ex);
        }catch (SQLException ex) {
            Logger.getLogger(FrmAsignaciones.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbEm = new javax.swing.JLabel();
        jLbListado = new javax.swing.JLabel();
        jComboListado = new javax.swing.JComboBox();
        jLbEstudiante = new javax.swing.JLabel();
        jTFEstudiante = new javax.swing.JTextField();
        jLbNumeroCaso = new javax.swing.JLabel();
        jTFNumeroCaso = new javax.swing.JTextField();
        jLBFechaAsignacion = new javax.swing.JLabel();
        jLbFechaRevocacion = new javax.swing.JLabel();
        jLBAsunto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAsunto = new javax.swing.JTextArea();
        jBTAsignar = new javax.swing.JButton();
        jBtSalir = new javax.swing.JButton();
        jBTReasignar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTblListado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLbEm.setText("Uso exclusivo del monitor");

        jLbListado.setText("Listado Usuarios");

        jComboListado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboListadoActionPerformed(evt);
            }
        });

        jLbEstudiante.setText("Estudiante Asignado");

        jTFEstudiante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFEstudianteKeyTyped(evt);
            }
        });

        jLbNumeroCaso.setText("Numero del caso");

        jTFNumeroCaso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFNumeroCasoKeyTyped(evt);
            }
        });

        jLBFechaAsignacion.setText("Fecha de asignacion");

        jLbFechaRevocacion.setText("Fecha de revocacion");

        jLBAsunto.setText("Asunto");

        jTAsunto.setColumns(20);
        jTAsunto.setRows(5);
        jTAsunto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTAsuntoKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTAsunto);

        jBTAsignar.setText("ASIGNAR");

        jBtSalir.setText("SALIR");
        jBtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSalirActionPerformed(evt);
            }
        });

        jBTReasignar.setText("REASIGNAR");

        jTblListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTblListado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jBTAsignar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(jBtSalir)
                .addGap(159, 159, 159)
                .addComponent(jBTReasignar)
                .addGap(319, 319, 319))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(jLbEm))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLbListado)
                                .addGap(95, 95, 95)
                                .addComponent(jComboListado, 0, 156, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLbEstudiante)
                                    .addComponent(jLbNumeroCaso)
                                    .addComponent(jLBFechaAsignacion)
                                    .addComponent(jLbFechaRevocacion))
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTFNumeroCaso, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                    .addComponent(jTFEstudiante))))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLBAsunto)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLbEm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbListado)
                            .addComponent(jComboListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbEstudiante)
                            .addComponent(jTFEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbNumeroCaso)
                            .addComponent(jTFNumeroCaso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(jLBFechaAsignacion)
                        .addGap(26, 26, 26)
                        .addComponent(jLbFechaRevocacion)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLBAsunto)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTReasignar)
                    .addComponent(jBtSalir)
                    .addComponent(jBTAsignar))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSalirActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_jBtSalirActionPerformed

    private void jComboListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboListadoActionPerformed
        // TODer.getLogger(FrmAsignaciones.class.getName()).log(Level.SEVERE, null, ex);
    
    
    }//GEN-LAST:event_jComboListadoActionPerformed

    private void jTFNumeroCasoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNumeroCasoKeyTyped
        // TODO add your handling code here:
        char  c = evt.getKeyChar();
        if((c<'0' || c>'9')) evt.consume();

        String cadena = jTFNumeroCaso.getText();
        if (cadena.length() >= 7) evt.consume();
    }//GEN-LAST:event_jTFNumeroCasoKeyTyped

    private void jTAsuntoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTAsuntoKeyTyped
        // TODO add your handling code here:
        char  c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z')) evt.consume();
    }//GEN-LAST:event_jTAsuntoKeyTyped

    private void jTFEstudianteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFEstudianteKeyTyped
        // TODO add your handling code here:
          char  c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z')) evt.consume();
    }//GEN-LAST:event_jTFEstudianteKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAsignaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAsignaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAsignaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAsignaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAsignaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBTAsignar;
    public javax.swing.JButton jBTReasignar;
    public javax.swing.JButton jBtSalir;
    public javax.swing.JComboBox jComboListado;
    private javax.swing.JLabel jLBAsunto;
    private javax.swing.JLabel jLBFechaAsignacion;
    private javax.swing.JLabel jLbEm;
    private javax.swing.JLabel jLbEstudiante;
    private javax.swing.JLabel jLbFechaRevocacion;
    private javax.swing.JLabel jLbListado;
    private javax.swing.JLabel jLbNumeroCaso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTAsunto;
    private javax.swing.JTextField jTFEstudiante;
    public javax.swing.JTextField jTFNumeroCaso;
    public javax.swing.JTable jTblListado;
    // End of variables declaration//GEN-END:variables
}
